# Generated by Django 3.0.5 on 2022-01-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpayment',
            name='admin',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='addpayment',
            name='loan_id',
            field=models.CharField(max_length=200),
        ),
    ]
