# Generated by Django 3.0.5 on 2022-01-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_auto_20220126_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpayment',
            name='paid',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
