# Generated by Django 3.0.5 on 2022-01-31 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_addpayment_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAddPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(max_length=200)),
                ('payment_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(max_length=200)),
                ('paid', models.CharField(max_length=200)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('admin', models.CharField(max_length=200)),
            ],
        ),
    ]
