# Generated by Django 2.2.12 on 2022-02-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_groupaddpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=200)),
                ('feedback', models.TextField(max_length=100000)),
            ],
        ),
    ]
