# Generated by Django 3.0 on 2022-06-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_auto_20220219_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addpayment',
            old_name='paid',
            new_name='status',
        ),
    ]
