# Generated by Django 3.0 on 2022-06-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_auto_20220612_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpayment',
            name='payment_fee',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
