# Generated by Django 3.0 on 2022-06-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0008_auto_20220612_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpayment',
            name='reference',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
