# Generated by Django 4.0.5 on 2022-06-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0009_addpayment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='feedback',
            field=models.TextField(max_length=200),
        ),
    ]
