# Generated by Django 4.0.5 on 2022-07-13 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0010_alter_replies_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPermitPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_id', models.CharField(default='null', max_length=200)),
                ('payment_fee', models.DecimalField(decimal_places=2, default='0', max_digits=20)),
                ('phone_number', models.CharField(default='null', max_length=20)),
                ('transaction_id', models.CharField(default='null', max_length=200)),
                ('status', models.CharField(default='null', max_length=200)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('admin', models.CharField(default='null', max_length=200)),
            ],
        ),
    ]
