# Generated by Django 4.0.5 on 2022-07-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0011_addpermitpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpermitpayment',
            name='reference',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
