# Generated by Django 4.0.5 on 2022-07-15 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0012_addpermitpayment_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_id', models.CharField(default='null', max_length=200)),
                ('uploaded_file', models.FileField(upload_to='')),
                ('message', models.TextField(default='null')),
                ('admin', models.CharField(default='null', max_length=30)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
