# Generated by Django 4.0.5 on 2023-04-18 17:25

import datetime
from django.db import migrations, models
import loan.models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0013_fileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodaApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boda_id', models.CharField(default=loan.models.random_string, max_length=200)),
                ('boda_guy_firstName', models.CharField(default='null', max_length=40)),
                ('boda_guy_lastName', models.CharField(default='null', max_length=40)),
                ('boda_numberPlate', models.CharField(default='null', max_length=10)),
                ('final_amount', models.DecimalField(decimal_places=2, default='0', max_digits=12)),
                ('deposits', models.DecimalField(decimal_places=2, default='0', max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default='0', max_digits=12)),
                ('weekly_pay', models.DecimalField(decimal_places=2, default='0', max_digits=12)),
                ('phone_number', models.CharField(default='null', max_length=15)),
                ('nin_number', models.CharField(default='null', max_length=30)),
                ('nin_picture', models.FileField(upload_to='')),
                ('work_stage', models.CharField(default='null', max_length=30)),
                ('guarantor1_name', models.CharField(default='null', max_length=30)),
                ('guarantor1_stage_name', models.CharField(default='null', max_length=30)),
                ('guarantor1_number', models.CharField(default='null', max_length=15)),
                ('guarantor1_nin', models.CharField(default='null', max_length=30)),
                ('guarantor1_nin_picture', models.FileField(upload_to='')),
                ('guarantor2_name', models.CharField(default='null', max_length=30)),
                ('guarantor2_stage_name', models.CharField(default='null', max_length=30)),
                ('guarantor2_number', models.CharField(default='null', max_length=15)),
                ('guarantor2_nin', models.CharField(default='null', max_length=30)),
                ('guarantor2_nin_picture', models.FileField(upload_to='')),
                ('guarantor3_name', models.CharField(default='null', max_length=30)),
                ('guarantor3_stage_name', models.CharField(default='null', max_length=30)),
                ('guarantor3_number', models.CharField(default='null', max_length=15)),
                ('guarantor3_nin', models.CharField(default='null', max_length=30)),
                ('guarantor3_nin_picture', models.FileField(upload_to='')),
                ('date_of_application', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('day_of_the_week', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
