# Generated by Django 4.0.5 on 2023-04-18 17:29

from django.db import migrations, models
import loan.models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0014_bodaapply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodaapply',
            name='boda_id',
            field=models.CharField(default=loan.models.random_string, max_length=200, unique=True),
        ),
    ]
