# Generated by Django 4.0.5 on 2023-04-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0018_bodaapply_latest_dateofpay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodaapply',
            name='guarantor1_nin_picture',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bodaapply',
            name='guarantor2_nin_picture',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bodaapply',
            name='guarantor3_nin_picture',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bodaapply',
            name='nin_picture',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
