# Generated by Django 4.0.5 on 2023-10-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0019_alter_bodaapply_guarantor1_nin_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodaapply',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=10),
        ),
    ]
