# Generated by Django 4.0.5 on 2024-05-26 12:31

from django.db import migrations, models
import loan.models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0021_cashflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='cash_id',
            field=models.CharField(default=loan.models.random_string, max_length=200),
        ),
    ]
