# Generated by Django 4.0.5 on 2024-05-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0022_alter_cashflow_cash_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodaInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberPlate', models.CharField(default='', max_length=200)),
                ('rider', models.CharField(default='', max_length=200)),
                ('amountBought', models.DecimalField(decimal_places=2, default='0', max_digits=20)),
                ('whereBought', models.CharField(default='', max_length=200)),
                ('LogBookNames', models.CharField(default='', max_length=200)),
                ('demandedAmount', models.DecimalField(decimal_places=2, default='0', max_digits=20)),
                ('isCompleted', models.BooleanField(default=False)),
            ],
        ),
    ]
