# Generated by Django 4.0.5 on 2026-03-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0023_bodainformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodaapply',
            name='initial_payment',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=12),
        ),
    ]
