# Generated by Django 4.0.5 on 2026-03-07 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0024_bodaapply_initial_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBodaSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('id_number', models.CharField(blank=True, default='', max_length=50)),
                ('number_plate', models.CharField(max_length=20)),
                ('amount_bought_at', models.DecimalField(decimal_places=2, default='0', max_digits=14)),
                ('amount_sold_for', models.DecimalField(decimal_places=2, default='0', max_digits=14)),
                ('date_sold', models.DateField(default=datetime.datetime.now)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
