# Generated by Django 4.0.5 on 2026-03-07 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0025_cashbodasale'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodaInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=20)),
                ('amount_bought_at', models.DecimalField(decimal_places=2, default='0', max_digits=14)),
                ('date_purchased', models.DateField(default=datetime.datetime.now)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('SOLD_CASH', 'Sold - Cash'), ('LOAN', 'Gone to Loan')], default='IN_STOCK', max_length=20)),
                ('buyer_name', models.CharField(blank=True, default='', max_length=100)),
                ('buyer_phone', models.CharField(blank=True, default='', max_length=20)),
                ('buyer_id', models.CharField(blank=True, default='', max_length=50)),
                ('amount_sold_for', models.DecimalField(decimal_places=2, default='0', max_digits=14)),
                ('date_sold', models.DateField(blank=True, null=True)),
                ('boda_apply_id', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CashBodaSale',
        ),
    ]
