# Generated by Django 4.0.5 on 2026-03-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0026_bodainventory_delete_cashbodasale'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodainventory',
            name='boda_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bodainventory',
            name='buyer_address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bodainventory',
            name='chassis_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bodainventory',
            name='colour',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bodainventory',
            name='engine_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
