# Generated by Django 4.0.5 on 2026-03-07 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0027_bodainventory_boda_type_bodainventory_buyer_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpoundedBike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boda_id', models.CharField(blank=True, default='', max_length=200)),
                ('number_plate', models.CharField(max_length=20)),
                ('client_name', models.CharField(max_length=100)),
                ('client_phone', models.CharField(blank=True, default='', max_length=20)),
                ('date_impounded', models.DateField(default=datetime.datetime.now)),
                ('amount_demanded', models.DecimalField(decimal_places=2, default='0', max_digits=14)),
                ('deficit_at_impound', models.DecimalField(decimal_places=2, default='0', max_digits=14)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('HELD', 'Being Held'), ('RETURNED', 'Returned')], default='HELD', max_length=20)),
                ('date_returned', models.DateField(blank=True, null=True)),
                ('return_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
