# Generated by Django 3.0.5 on 2022-01-21 13:21

import datetime
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('national_id', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=200)),
                ('pic_id', models.FileField(upload_to='')),
                ('person_pic', models.FileField(upload_to='')),
                ('first_guarrante_full_names', models.CharField(max_length=200)),
                ('first_guarrante_national_id', models.CharField(max_length=200)),
                ('first_guarrante_telephone', models.CharField(max_length=200)),
                ('first_guarrante_pic_id', models.FileField(upload_to='')),
                ('second_guarrante_full_names', models.CharField(max_length=200)),
                ('second_guarrante_national_id', models.CharField(max_length=200)),
                ('second_guarrante_telephone', models.CharField(max_length=200)),
                ('second_guarrante_pic_id', models.FileField(upload_to='')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('loan_id', models.CharField(default=home.models.random_string, max_length=10000000000)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('user', models.CharField(max_length=200)),
            ],
        ),
    ]
