# Generated by Django 3.0.5 on 2022-01-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_apply_transction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='payback',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
    ]
