# Generated by Django 3.0.5 on 2022-01-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_apply_payback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='payback',
        ),
    ]
