# Generated by Django 3.0.5 on 2022-01-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_apply_payback'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='payback',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=12),
        ),
    ]
