# Generated by Django 3.0.5 on 2022-01-31 11:52

import datetime
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_apply_payback'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(default=home.models.random_string, max_length=1000000000)),
                ('first_person_full_names', models.CharField(default='null', max_length=200)),
                ('first_person_telephone', models.CharField(default='xxx', max_length=200)),
                ('first_person_national_id', models.CharField(default='null', max_length=200)),
                ('first_person_national_id_pic', models.FileField(upload_to='')),
                ('first_person_pic', models.FileField(upload_to='')),
                ('second_person_full_names', models.CharField(default='null', max_length=200)),
                ('second_person_telephone', models.CharField(default='xxx', max_length=200)),
                ('second_person_national_id', models.CharField(default='null', max_length=200)),
                ('second_person_national_id_pic', models.FileField(upload_to='')),
                ('second_person_pic', models.FileField(upload_to='')),
                ('third_person_full_names', models.CharField(default='null', max_length=200)),
                ('third_person_telephone', models.CharField(default='xxx', max_length=200)),
                ('third_person_national_id', models.CharField(default='null', max_length=200)),
                ('third_person_national_id_pic', models.FileField(upload_to='')),
                ('third_person_pic', models.FileField(upload_to='')),
                ('fourth_person_full_names', models.CharField(default='null', max_length=200)),
                ('fourth_person_telephone', models.CharField(default='xxx', max_length=200)),
                ('fourth_person_national_id', models.CharField(default='null', max_length=200)),
                ('fourth_person_national_id_pic', models.FileField(upload_to='')),
                ('fourth_person_pic', models.FileField(upload_to='')),
                ('status', models.CharField(default='pending', max_length=50)),
                ('user', models.CharField(max_length=200)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payback', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
            ],
        ),
    ]
