# Generated by Django 3.0.5 on 2022-01-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_groupapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupapply',
            name='general_number',
            field=models.CharField(default='xxx', max_length=20),
        ),
    ]
