# Generated by Django 3.0.5 on 2022-02-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_groupapply_general_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=1000)),
                ('question', models.CharField(max_length=10000)),
            ],
        ),
    ]
