# Generated by Django 2.2.12 on 2022-02-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='answered',
            field=models.CharField(default='NO', max_length=10),
        ),
    ]
