# Generated by Django 3.0 on 2022-06-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_support_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='reference',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
