# Generated by Django 3.0 on 2022-06-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_apply_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='status',
            field=models.CharField(default='fee_not_paid', max_length=50),
        ),
    ]
