# Generated by Django 4.0.5 on 2022-07-10 10:46

import datetime
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_apply_loan_id_alter_groupapply_loan_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_id', models.CharField(default=home.models.random_string, max_length=200)),
                ('first_name', models.CharField(default='null', max_length=200)),
                ('last_name', models.CharField(default='null', max_length=200)),
                ('service', models.CharField(default='null', max_length=200)),
                ('phone_number', models.CharField(default='0000000', max_length=20)),
                ('date_modified', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('message', models.CharField(default='null', max_length=200)),
                ('final_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
                ('deposits', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
            ],
        ),
    ]
