# Generated by Django 4.0.5 on 2022-07-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_permitapply_balance_alter_permitapply_deposits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='balance',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=12),
        ),
        migrations.AddField(
            model_name='apply',
            name='deposits',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=12),
        ),
    ]
