# Generated by Django 4.0.5 on 2023-01-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_apply_balance_apply_deposits'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitapply',
            name='admin',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
