# Generated by Django 4.0.5 on 2023-04-18 17:34

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_permitapply_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitapply',
            name='permit_id',
            field=models.CharField(default=home.models.random_string, max_length=200, unique=True),
        ),
    ]
